Dataset:
  Audioset:
    train:
      sample_path: "/home/mux/code_workspace/multi-ae-ace/data/audioset/train"
      json_path: "/home/mux/code_workspace/multi-ae-ace/data/audioset/train/AudioSet.json"
    eval:
      sample_path: "/home/mux/code_workspace/multi-ae-ace/data/udioset/eval"
      json_path: "/home/mux/code_workspace/multi-ae-ace/data/audioset/eval/AudioSet.json"