services:
  multi_ae_ace:
    build:
      context: ../../
      dockerfile: docker/gpu/Dockerfile
      args:
        - PY_VERSION=3.11
    container_name: multi_ae_ace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ../../:/workspace
      # - ./data/: "<container_dataset>"
    tty: true
