TrainProcessControl:
  Epoch: 300
  BatchSize: 1280
  LearningRate: 1e-3
  Optimizer:
    Type: Adam
    WeightDecay: 5e-5
  Scheduler:
    Type: ReduceLROnPlateau
    patience: 10
  device: cuda
  val_interval: 5

ToLogMelSpectrogram:
  sample_rate: 16000
  n_fft: 400
  hop_length: 160
  n_mels: 80

TimeSequenceLengthFixer:
  mode: s
  fixed_length: 5 #s, same as dataset
  sample_rate: 16000

Resample:
  orig_freq: 44100
  new_freq: 16000

SoundTrackSelector:
  mode: mix

AutoEncoder:
  n_mel: 80
  latent_size: 300
  num_heads: 2
  AutoEncoderInitDummyInput:
    shape: [1, 80, 501]
DatasetInfo:
  duration: 10 # s
CacheableDataset:
  max_cache_size: 20000
  multiprocessing: False
  device: cuda
